controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

controllers_api_admin:
    resource: ../src/Controller/Admin/Api/Protected
    type: attribute
    prefix: /api/admin
    name_prefix: api_admin_

admin_ui_controllers:
    resource: ../src/Admin/UI/API/
    type: attribute
    prefix: /api/admin
    name_prefix: api_admin_

controllers_shop_api:
    resource: ../src/Controller/Shop/Api/
    type: attribute
    prefix: /api/shop
    name_prefix: shop_api_

api_login_check:
    path: /api/login

