shop_web_controllers:
    resource: ../src/Shop/UI/Web/
    type: attribute

domain_controllers:
    resource: '../src/'
    type: attribute

shop_api_controllers:
    resource: ../src/Shop/UI/API/
    type: attribute
    prefix: /api/shop
    name_prefix: shop_api_

api_login_check:
    path: /api/login

